### PR TITLE
UPSTREAM: 000000: this should be replaced by Mo's upstream PR

### PR DESCRIPTION
**Pull request by soltysh**
@enj I didn't want to change storage.go files, but that what we've talked about, pls double check if that's sufficient.

### CODE REVIEW

**Comment by enj** [comment]
LGTM 👍 

Once our code starts using `CompleteWithOptions` we will find out pretty quickly if we missed anything.  How soon do we need this upstream?

**Comment by soltysh** [comment]
> How soon do we need this upstream?

The usual as soon as possible, since it'll take some time go get it in and currently the merge queue for 1.7 hasn't opened yet.

**Comment by sttts** [comment]
@enj `CompleteWithOptions` is approaching: https://github.com/sttts/origin/pull/10/commits/9807f63c34449907b685df77d6a2fe6fef615ede

**Comment by enj** [comment]
xref https://github.com/kubernetes/kubernetes/pull/44779

**Pull request merged**
